[tool.black]
line-length = 120
target-version = ['py311']
extend-exclude = '''
    migration/
    | test_data.py
'''

[tool.isort]
profile = "black"
include_trailing_comma = true
line_length = 120
lines_after_imports = 2
skip = ["__init__.py", "venv", "alembic", "docker", ".git", "__pycache__", "migration"]

[tool.flake8]
exclude = ["__init__.py", "venv", "alembic", "docker", ".git", "__pycache__", "migration"]
max-line-length = 120
ignore = ["E203", "E266", "E501", "W503"]


